version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    environment:
       ELASTICSEARCH_URL: http://172.19.0.2:9200
    ports:
      - 5601:5601
    networks:
      - esnet

networks:
  esnet:

